# -*- coding: utf-8 -*-
"""Copy of BreastCancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AphhJViEJuAZpknlatCI_d2a3qexpPPK
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive"))

import zipfile
import os

ZIP_PATH = "/content/drive/MyDrive/datasets.zip"
EXTRACT_PATH = "/content/data"

os.makedirs(EXTRACT_PATH, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print("Dataset extracted successfully!")

import os

BASE_DIR = "/content/data/datasets"

valid_folders = []

for folder in os.listdir(BASE_DIR):
    folder_path = os.path.join(BASE_DIR, folder)
    if os.path.isdir(folder_path) and len(os.listdir(folder_path)) > 0:
        valid_folders.append(folder)
    else:
        print(f"Skipping empty folder: {folder}")

print("Using folders:", valid_folders)

import shutil

FINAL_DATASET = "/content/final_dataset"
benign_path = os.path.join(FINAL_DATASET, "benign")
malignant_path = os.path.join(FINAL_DATASET, "malignant")

os.makedirs(benign_path, exist_ok=True)
os.makedirs(malignant_path, exist_ok=True)

def copy_images(src_folder):
    for root, _, files in os.walk(src_folder):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                label = "malignant" if "mal" in root.lower() else "benign"
                dest = malignant_path if label == "malignant" else benign_path
                shutil.copy(os.path.join(root, file), dest)

for folder in valid_folders:
    copy_images(os.path.join(BASE_DIR, folder))

print("Images organized into benign / malignant")

import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

IMG_SIZE = (160, 160)   # reduced
BATCH_SIZE = 8          # reduced

train_ds = tf.keras.utils.image_dataset_from_directory(
    FINAL_DATASET,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    FINAL_DATASET,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

train_ds = train_ds.shuffle(500).prefetch(1)
val_ds = val_ds.prefetch(1)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05)
])

base_model = tf.keras.applications.ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(160, 160, 3)
)

base_model.trainable = False

model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255),
    data_augmentation,
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

callbacks = [
    tf.keras.callbacks.CSVLogger('/content/training_log.csv'),
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True
    )
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=callbacks,
    verbose=1
)

import matplotlib.pyplot as plt

# Extract final values from ResNet50 history
train_acc = history.history['accuracy'][-1] * 100
val_acc = history.history['val_accuracy'][-1] * 100
train_loss = history.history['loss'][-1]
val_loss = history.history['val_loss'][-1]

plt.figure(figsize=(12,5))

# Accuracy plot
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy', marker='o')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', marker='o')
plt.legend()
plt.title("ResNet50 Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.grid(True)

# Accuracy text box
plt.text(
    0.95, 0.05,
    f"Train Acc: {train_acc:.2f}%\nVal Acc: {val_acc:.2f}%",
    transform=plt.gca().transAxes,
    ha='right',
    va='bottom',
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8)
)

# Loss plot
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss', marker='o')
plt.plot(history.history['val_loss'], label='Validation Loss', marker='o')
plt.legend()
plt.title("ResNet50 Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.grid(True)

# Loss text box
plt.text(
    0.95, 0.05,
    f"Train Loss: {train_loss:.4f}\nVal Loss: {val_loss:.4f}",
    transform=plt.gca().transAxes,
    ha='right',
    va='bottom',
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8)
)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Final accuracy values from ResNet50 history
train_acc = history.history['accuracy'][-1] * 100
val_acc = history.history['val_accuracy'][-1] * 100

# Bar graph data
labels = ['ResNet50 Training Accuracy', 'ResNet50 Validation Accuracy']
accuracy_values = [train_acc, val_acc]

plt.figure(figsize=(6,4))
plt.bar(labels, accuracy_values)

plt.title('ResNet50 Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.ylim(0, 100)

# Show accuracy values on bars
for i, value in enumerate(accuracy_values):
    plt.text(i, value + 1, f"{value:.2f}%", ha='center', fontweight='bold')

plt.grid(axis='y')
plt.show()

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

y_true = np.concatenate([y for x, y in val_ds], axis=0)
y_pred = model.predict(val_ds)
y_pred = (y_pred > 0.5).astype(int)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))





import tensorflow as tf
import matplotlib.pyplot as plt

IMG_SIZE = (160, 160)
BATCH_SIZE = 8

train_ds = tf.keras.utils.image_dataset_from_directory(
    FINAL_DATASET,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    FINAL_DATASET,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

train_ds = train_ds.shuffle(500).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.prefetch(tf.data.AUTOTUNE)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
])

cnn_model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255, input_shape=(160, 160, 3)),
    data_augmentation,

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(1, activation='sigmoid')
])

cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

cnn_model.summary()

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True
    ),
    tf.keras.callbacks.CSVLogger('/content/cnn_training_log.csv')
]

history_cnn = cnn_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=callbacks,
    verbose=1
)

train_acc = history_cnn.history['accuracy'][-1] * 100
val_acc = history_cnn.history['val_accuracy'][-1] * 100

plt.figure(figsize=(6,4))
plt.plot(history_cnn.history['accuracy'], label='Train Accuracy')
plt.plot(history_cnn.history['val_accuracy'], label='Validation Accuracy')
plt.title("Custom CNN Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)

plt.text(
    0.95, 0.05,
    f"Train Acc: {train_acc:.2f}%\nVal Acc: {val_acc:.2f}%",
    transform=plt.gca().transAxes,
    ha='right',
    va='bottom',
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8)
)

plt.show()

import matplotlib.pyplot as plt

# Final accuracy values from CNN history
train_acc = history_cnn.history['accuracy'][-1] * 100
val_acc = history_cnn.history['val_accuracy'][-1] * 100

# Data for bar graph
labels = ['Training Accuracy', 'Validation Accuracy']
accuracy_values = [train_acc, val_acc]

plt.figure(figsize=(6,4))
plt.bar(labels, accuracy_values)

plt.title('Custom CNN Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.ylim(0, 100)

# Display values on bars
for i, v in enumerate(accuracy_values):
    plt.text(i, v + 1, f"{v:.2f}%", ha='center', fontweight='bold')

plt.grid(axis='y')
plt.show()

"""1️⃣ VGG16

"""

base_vgg = tf.keras.applications.VGG16(
    weights='imagenet',
    include_top=False,
    input_shape=(160,160,3)
)
base_vgg.trainable = False

vgg16_model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255),
    base_vgg,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

vgg16_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_vgg16 = vgg16_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    verbose=1
)

import matplotlib.pyplot as plt

# Extract final accuracy values
train_acc = history_vgg16.history['accuracy'][-1] * 100
val_acc = history_vgg16.history['val_accuracy'][-1] * 100

# Data for bar graph
labels = ['VGG16 Training Accuracy', 'VGG16 Validation Accuracy']
accuracy_values = [train_acc, val_acc]

plt.figure(figsize=(6,4))
plt.bar(labels, accuracy_values)

plt.title('VGG16 Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.ylim(0, 100)

# Show values on bars
for i, acc in enumerate(accuracy_values):
    plt.text(i, acc + 1, f"{acc:.2f}%", ha='center', fontweight='bold')

plt.grid(axis='y')
plt.show()

"""2️⃣ MobileNetV2 (Lightweight network)

"""

base_mobilenet = tf.keras.applications.MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(160,160,3)
)
base_mobilenet.trainable = False

mobilenet_model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255),
    base_mobilenet,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

mobilenet_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_mobilenet = mobilenet_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    verbose=1
)

import matplotlib.pyplot as plt

# Extract final accuracy values
train_acc = history_mobilenet.history['accuracy'][-1] * 100
val_acc = history_mobilenet.history['val_accuracy'][-1] * 100

# Data for bar graph
labels = ['MobileNetV2 Training Accuracy', 'MobileNetV2 Validation Accuracy']
accuracy_values = [train_acc, val_acc]

plt.figure(figsize=(6,4))
plt.bar(labels, accuracy_values)

plt.title('MobileNetV2 Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.ylim(0, 100)

# Display accuracy values on bars
for i, acc in enumerate(accuracy_values):
    plt.text(i, acc + 1, f"{acc:.2f}%", ha='center', fontweight='bold')

plt.grid(axis='y')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

class_names = ["Non-Cancer (IDC-)", "Cancer (IDC+)"]

model = mobilenet_model   # or vgg16_model

plt.figure(figsize=(12,12))
count = 0

for images, labels in val_ds:
    probs = model.predict(images).reshape(-1)
    preds = (probs > 0.5).astype(int)

    for i in range(images.shape[0]):
        if labels[i] == preds[i] and count < 9:
            ax = plt.subplot(3,3,count+1)

            # 🔥 Colored display (pseudo-color)
            plt.imshow(images[i].numpy()[:,:,0], cmap='jet')
            plt.axis("off")

            plt.title(
                f"Correct\n{class_names[int(preds[i])]}\nConf: {probs[i]*100:.2f}%",
                color="green"
            )

            count += 1

    if count >= 9:
        break

plt.suptitle("Correct Predictions (Colored)", fontsize=16)
plt.show()

plt.figure(figsize=(12,12))
count = 0

for images, labels in val_ds:
    probs = model.predict(images).reshape(-1)
    preds = (probs > 0.5).astype(int)

    for i in range(images.shape[0]):
        if labels[i] != preds[i] and count < 9:
            ax = plt.subplot(3,3,count+1)

            # 🔥 Colored display (pseudo-color)
            plt.imshow(images[i].numpy()[:,:,0], cmap='jet')
            plt.axis("off")

            plt.title(
                f"True: {class_names[int(labels[i])]}\n"
                f"Pred: {class_names[int(preds[i])]}\n"
                f"Conf: {probs[i]*100:.2f}%",
                color="red"
            )

            count += 1

    if count >= 9:
        break

plt.suptitle("Misclassified Samples (Colored)", fontsize=16)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

class_names = ["Non-Cancer (IDC-)", "Cancer (IDC+)"]

model = mobilenet_model   # or vgg16_model

plt.figure(figsize=(12,12))

for images, labels in val_ds.take(1):
    probs = model.predict(images).reshape(-1)
    preds = (probs > 0.5).astype(int)

    num_images = min(9, images.shape[0])

    for i in range(num_images):
        ax = plt.subplot(3,3,i+1)

        # Display image (colored pseudo-color)
        plt.imshow(images[i].numpy()[:,:,0], cmap='jet')
        plt.axis("off")

        # Decision
        decision = "CANCER DETECTED ✅" if preds[i] == 1 else "NO CANCER ❌"

        plt.title(
            f"{decision}\n"
            f"Confidence: {probs[i]*100:.2f}%",
            color="red" if preds[i] == 1 else "green"
        )

plt.suptitle("Cancer Prediction Results", fontsize=16)
plt.show()

for images, labels in val_ds.take(1):
    prob = model.predict(images)[0][0]
    if prob > 0.5:
        print(f"Cancer Detected (Confidence: {prob*100:.2f}%)")
    else:
        print(f"No Cancer Detected (Confidence: {(1-prob)*100:.2f}%)")

